### ISSUE TITLE
Error during Training 

### ISSUE THREAD

**Issue by Threepointone4** [fabrahman/ReBART#6]
I have created both dev.jsonl and train_data.jsonl in the format shared in the issue : [link](https://drive.google.com/drive/folders/1bY7CvXF1q2kgpmtXWtD0NT3bFRfLHpV1) , its giving :

06/20/2022 13:50:00 - INFO - __main__ - Converting to token IDs
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/ReBART/source/encoder_decoder.py", line 415, in <module>
    main()
  File "/content/ReBART/source/encoder_decoder.py", line 337, in main
    tokenizer, args, file_path=args.eval_data_file, block_size=args.block_size)
  File "/content/ReBART/source/encoder_decoder.py", line 39, in __init__
    examples = load_data(file_path, args.task)
  File "/content/ReBART/source/common.py", line 51, in load_data
    for line in all_lines
  File "/content/ReBART/source/common.py", line 51, in <listcomp>
    for line in all_lines
TypeError: list indices must be integers or slices, not str

**Comment by Threepointone4** [comment]
It was conversion from json to jsonl issue. Closing this as its resolved.
